let quote = [
{0:"When you give joy to other people, you get more joy in return. You should give a good thought to happiness that you can give out." },
{1:"When you change your thoughts, remember to also change your world." },
{2:"It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest. "},
{3:"Nature has given us all the pieces required to achieve exceptional wellness and health, but has left it to us to put these pieces together." },
{4:"We cannot solve problems with the kind of thinking we employed when we came up with them." },
{5:"Learn as if you will live forever, live like you will die tomorrow." },
{6:"Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too." },
{7:"Success is not final; failure is not fatal: It is the courage to continue that counts" },
{8:"Success is not final; failure is not fatal: It is the courage to continue that counts" },
{9:"It is better to fail in originality than to succeed in imitation" },
{10:"The road to success and the road to failure are almost exactly the same" },
{11:"Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. The slogan 'Press On' has solved and always will solve the problems of the human race" },
{12:"There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind." },
{13:"Success usually comes to those who are too busy looking for it." },
{14:"Develop success from failures. Discouragement and failure are two of the surest stepping stones to success." },
{15:"Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable." },
{16:"I never dreamed about success. I worked for it." },
{17:"Success is getting what you want, happiness is wanting what you get." },
{18:"The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty" },
{19:"Don’t let yesterday take up too much of today." },
{20:"You learn more from failure than from success. Don’t let it stop you. Failure builds character." },
{21:"If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you." },
{22:"Experience is a hard teacher because she gives the test first, the lesson afterwards." },
{23:"To know how much there is to know is the beginning of learning to live." },
{24:"Goal setting is the secret to a compelling future." },
{25:"Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus. " },
{26:"Either you run the day or the day runs you." },
{27:"I’m a greater believer in luck, and I find the harder I work the more I have of it." },
{28:"When we strive to become better than we are, everything around us becomes better too." },
{29:"Opportunity is missed by most people because it is dressed in overalls and looks like work." },
{30:"Setting goals is the first step in turning the invisible into the visible." },
{31:"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it." },
{32:"It’s not about better time management. It’s about better life management" },
{33:"Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness." },
{34:"The strongest actions for a woman is to love herself, be herself and shine amongst those who never believed she could." },
{35:"Whenever you see a successful woman, look out for three men who are going out of their way to try to block her." },
{36:"Some women choose to follow men, and some choose to follow their dreams. If you’re wondering which way to go, remember that your career will never wake up and tell you that it doesn’t love you anymore." },
{37:"The thing women have yet to learn is nobody gives you power. You just take it. " },
{38:"No woman wants to be in submission to a man who isn’t in submission to God!" },
{39:"A witty woman is a treasure; a witty beauty is a power." },
{40:"When a woman becomes her own best friend life is easier." },
{41:"If you want something said, ask a man; if you want something done, ask a woman." },
{42:"We need women at all levels, including the top, to change the dynamic, reshape the conversation, to make sure women’s voices are heard and heeded, not overlooked and ignored." },
{43:"It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent." },
{44:"Women must learn to play the game as men do." },
{45:"I swear, by my life and my love of it, that I will never live for the sake of another man, nor ask another man to live for mine." },
{46:"He who conquers himself is the mightiest warrior." },
{47:"Try not to become a man of success, but rather become a man of value." },
{48:"One man with courage makes a majority." },
{49:"One secret of success in life is for a man to be ready for his opportunity when it comes." },
{50:"A man who has committed a mistake and doesn’t correct it is committing another mistake." },
{51:"The successful man will profit from his mistakes and try again in a different way." },
{52:"A successful man is one who can lay a firm foundation with the bricks others have thrown at him." },
{53:"He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has." },
{54:"Education is the most powerful weapon which you can use to change the world." },
{55:"You've got to get up every morning with determination if you're going to go to bed with satisfaction." },
{56:"Education is the most powerful weapon which you can use to change the world." },
{57:"The most difficult thing is the decision to act, the rest is merely tenacity." },
{58:"You’ll find that education is just about the only thing lying around loose in this world, and it’s about the only thing a fellow can have as much of as he’s willing to haul away." },
{59:"Take the attitude of a student, never be too big to ask questions, never know too much to learn something new." },
{60:"People often say that motivation doesn’t last. Well, neither does bathing – that’s why we recommend it daily." },
{61:"The elevator to success is out of order. You’ll have to use the stairs, one step at a time." },
{62:"Be a positive energy trampoline – absorb what you need and rebound more back." },
{63:"People often say that motivation doesn’t last. Well, neither does bathing – that’s why we recommend it daily." },
{64:"Work until your bank account looks like a phone number." },
{65:"I am so clever that sometimes I don’t understand a single word of what I am saying." },
{66:"People say nothing is impossible, but I do nothing every day." },
{67:"Life is like a sewer… what you get out of it depends on what you put into it." },
{68:"I always wanted to be somebody, but now I realise I should have been more specific." },
{69:"Talent wins games, but teamwork and intelligence win championships." },
{70:"Talent wins games, but teamwork and intelligence win championships." },
{71:"Individual commitment to a group effort—that is what makes a team work, a company work, a society work, a civilisation work." },
{72:"Teamwork is the ability to work together toward a common vision. The ability to direct individual accomplishments toward organizational objectives. It is the fuel that allows common people to attain uncommon results." },
{73:"Coming together is a beginning. Keeping together is progress. Working together is success." },
{74:"Alone we can do so little, together we can do so much." },
{75:"Remember, teamwork begins by building trust. And the only way to do that is to overcome our need for invulnerability." },
{76:"I invite everyone to choose forgiveness rather than division, teamwork over personal ambition." },
{77:"Just one small positive thought in the morning can change your whole day." },
{78:"Opportunities don't happen, you create them." },
{79:"Love your family, work super hard, live your passion." },
{80:"It is never too late to be what you might have been." },
{81:"Don't let someone else's opinion of you become your reality" },
{82:"If you’re not positive energy, you’re negative energy." },
{83:"I am not a product of my circumstances. I am a product of my decisions." },
{84:"Your Monday morning thoughts set the tone for your whole week. See yourself getting stronger, and living a fulfilling, happier & healthier life." },
{85:"The greatest discovery of my generation is that a human being can alter his life by altering his attitudes." },
{86:"One of the differences between some successful and unsuccessful people is that one group is full of doers, while the other is full of wishers." },
{87:"I’d rather regret the things I’ve done than regret the things I haven’t done." },
{88:"You cannot plow a field by turning it over in your mind. To begin, begin" },
{89:"When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love…" },
{90:"Mondays are the start of the work week which offer new beginnings 52 times a year!." },
{91:"Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice." },
{92:"Your Monday morning thoughts set the tone for your whole week. See yourself getting stronger, and living a fulfilling, happier & healthier life." },
{93:"Friday sees more smiles than any other day of the workweek!" },
{94:"Oh! It’s Friday again. Share the love that was missing during the week. In a worthy moment of peace and bliss." },
{95:"Every Friday, I like to high five myself for getting through another week on little more than caffeine, willpower, and inappropriate humor." },
{96:"Make a Friday a day to celebrate work well done that you can be proud of knowing that you just didn’t put in time to the next paycheck." },
{97:"When you leave work on Friday, leave work. Don’t let technology follow you throughout your weekend (answering text messages and emails) take a break you will be more refreshed to begin the workweek if you have had a break." },
{98:"You can get everything in life you want if you will just help enough other people get what they want." },
{99:"Inspiration does exist, but it must find you working." },
{100:"Don't settle for average. Bring your best to the moment. Then, whether it fails or succeeds, at least you know you gave all you had." },
{101:"Show up, show up, show up, and after a while the muse shows up, too." },
{102:"Don't bunt. Aim out of the ballpark. Aim for the company of immortals." },
{103:"I have stood on a mountain of no’s for one yes." },
{104:"If you believe something needs to exist, if it's something you want to use yourself, don't let anyone ever stop you from doing it." },
{105:"Don't look at your feet to see if you are doing it right. Just dance." },
{106:"Someone's sitting in the shade today because someone planted a tree a long time ago." },
{107:"True freedom is impossible without a mind made free by discipline." },
{108:"Rivers know this: there is no hurry. We shall get there some day." },
{109:"There is a vitality, a life force, an energy, a quickening that is translated through you into action, and because there is only one of you in all time, this expression is unique. And if you block it, it will never exist through any other medium and will be lost." },
{110:"Small is not just a stepping-stone. Small is a great destination itself." },
{111:"He that can have patience can have what he will." },
{112:"The only one who can tell you “you can’t win" },
{113:"Set your goals high, and don’t stop till you get there." },
{114:"Take your victories, whatever they may be, cherish them, use them, but don’t settle for them." },
{115:"Life can be much broader once you discover one simple fact: Everything around you that you call life was made up by people that were no smarter than you. And you can change it, you can influence it… Once you learn that, you'll never be the same again." },
{116:"Life is like riding a bicycle. To keep your balance you must keep moving." },
{117:"What you do speaks so loudly that I cannot hear what you say." },
{118:"I have never let my schooling interfere with my education." },
{119:"If you can't yet do great things, do small things in a great way." },
{120:"If you really want to do something, you'll find a way. If you don't, you'll find an excuse." },
{121:"Be sure you put your feet in the right place, then stand firm." },
{122:"Live out of your imagination, not your history." },
{123:"Do not wait for the perfect time and place to enter, for you are already onstage." },
{124:"The greater the difficulty, the more the glory in surmounting it." },
{125:"Courage doesn't always roar. Sometimes courage is a quiet voice at the end of the day saying, 'I will try again tomorrow'" },
{126:"If the decisions you make about where you invest your blood, sweat, and tears are not consistent with the person you aspire to be, you’ll never become that person." },
{127:"I will not lose, for even in defeat, there’s a valuable lesson learned, so it evens up for me." },
{128:"Fear of what other people will think is the single most paralyzing dynamic in business and in life. The best moment of my life was the day I realized that I no longer give a damn what anybody thinks. That’s enormously liberating and freeing, and it’s the only way to live your life and do your business" },
{129:"The only way of discovering the limits of the possible is to venture a little way past them into the impossible." },
{130:"Worry is a misuse of imagination" },
{131:"Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently." },
{132:"I never look back, darling. It distracts from the now" },
{133:"A year from now you will wish you had started today" },
{134:"The reason we struggle with insecurity is because we compare our behind-the-scenes with everyone else’s highlight reel" },
{135:"Somewhere, something incredible is waiting to be known." },
{136:"I will not lose, for even in defeat, there’s a valuable lesson learned, so it evens up for me." },
{137:"I do not try to dance better than anyone else. I only try to dance better than myself." },
{138:"If you don’t risk anything, you risk even more." },
{139:"Failure is simply the opportunity to begin again, this time more intelligently." },
{140:"Our greatest glory is not in never falling, but in rising every time we fall." },
{141:"If you change the way you look at things, the things you look at change." },
{142:"We must reach out our hand in friendship and dignity both to those who would befriend us and those who would be our enemy." },
{143:"It's fine to celebrate success but it is more important to heed the lessons of failure." },
{144:"I can’t tell you how many times I’ve been given a no. Only to find that a better, brighter, bigger yes was right around the corner." },
{145:"We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success." },
{146:"When everything seems to be going against you, remember that the airplane takes off against the wind, not with it." },
{147:"You cannot always control what goes on outside. But you can always control what goes on inside." },
{148:"We are what we repeatedly do. Excellence, then, is not an act, but a habit." },
{149:"Start where you are. Use what you have. Do what you can." },
{150:"Hustle beats talent when talent doesn’t hustle" },
{151:"Everything you've ever wanted is sitting on the other side of fear." },
{152:"The question isn't who is going to let me; it's who is going to stop me." },
{153:"Every strike brings me closer to the next home run." },
{154:"I have not failed. I've just found 10,000 ways that won't work." },
{155:"Don’t worry about failure; you only have to be right once." },
{156:"You carry the passport to your own happiness." },
{157:"Never let success get to your head and never let failure get to your heart." },
{158:"Ideation without execution is delusion." },
{159:"Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway." },
{160:"Make sure your worst enemy doesn’t live between your own two ears." },
{161:"It is a rough road that leads to the heights of greatness." },
{162:"For the great doesn’t happen through impulse alone, and is a succession of little things that are brought together." },
{163:"If we take care of the moments, the years will take care of themselves." },
{164:"Resilience is when you address uncertainty with flexibility." },
{165:"Sometimes magic is just someone spending more time on something than anyone else might reasonably expect." },
{166:"It’s not the will to win that matters—everyone has that. It’s the will to prepare to win that matters." },
{167:"As a single footstep will not make a path on the earth, so a single thought will not make a pathway in the mind. To make a deep physical path, we walk again and again. To make a deep mental path, we must think over and over the kind of thoughts we wish to dominate our lives." },
{168:"Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway." },
{169:"True humility is not thinking less of yourself; it is thinking of yourself less." },]
const q = document.getElementById('quote');
for (let i = 0; i < quote.length; i++) {task(i);}
function task(i) { setTimeout(function() { q.innerHTML = quote[i][i];}, 4000 * i); } 